### ISSUE TITLE
User Story: Portable Deployment of Service

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#11]
As an **operator**, I **would like to** develop a portable and distributed WES/TES service that can be deployed as an appliance in multiple cloud providers, **so that** I can provide it as ready-to-deploy product to new ELIXIR nodes (DE, CH, IT)

**Comment by giannidallatorre** [comment]
# Introduction

Kubernetes has been chosen to as the container orchestrator because of its wide adoption and increasing popularity.
It offers functionalities to manage the entire life-cycle of the services that are deployed on top of it and provides a common layer over various cloud providers and in-house deployment.

A goal for TESK is to provide simple deployment instructions, that can be used in heterogeneous environments with minimal configuration required if any

This objective has already been achieved for what concerns the core TESK service inside a Kubernetes where we have a full administrator rule. This assumption is quite strong and we need further investigations to set a proper line between the necessary rights and possibly provide a receipt that includes them. 

Up to now the most demanding part of what concerns the deployment, is the exposition of the services, this can be an easy task when Kubernetes takes advantages of external services (cloud  load balancer) or integrated services (using OpenShift functionality), differently it requires more assumptions and tuning in the case we can not take advantage of these services.
In this last scenario, when we expose the service using a public IP an option is to provide it through a Nginx ingress docker-server, which can act also as a load balancer and a proxy server. The Nginx server requires to be exposed through a static external IP and the underlying network wiring are demanded to the Kubernetes network plugin.
A Kubernetes installation (IaaS) does not define the network plugin which has to be chosen during the installation, from our limited experience the effectiveness of them is not uniform and some of them does not provide the same level of functionality of the others.

In the case of a local-machine deployment of TESK, MiniKube is the recommended method for creating a local, single-node Kubernetes cluster for development and testing. In this case exposition of the service would be simulated, providing the service through a private address of the local host, connected to the local Kubernetes subnet.

Kubernetes deployments are usually defined using YAML file (JSON is accepted as well) and they have supported only a static reference, so there is no concept of variables, therefore each deployment must have his own site-specific YAML files.
To overcome this limitation we are providing Jinja2 templates that will produce YAML files, populating the variable using a single INI file as a dictionary reference.

The expected workflow for a new TESK deployment consists of this steps:
Cloning the TESK repository
Choosing the folder relative to Kubernetes environment (OpenShift, OpenStack, GCP, MiniKube...)
Edit the INI file with the site-specific values
Produce the expected YAML files, executing a single command of the Jinja2 CLI
Deploy all the TESK pods and services, executing a single command of the Kubernetes CLI (or alternatively the OpenShift CLI). 

# Planned activities
## Short Term
-   [ ] Update the templates for OpenStack
-   [ ] Update the templates for OpenShift
-   [ ] Validate the adoption of the Jinja2 templates (Done)
-   [ ] Remove the static code and relative documentation (in progress)
-   [ ] Provide a unified deployment documentation reflecting the last updates (in progress)
## Automation of the Deployment 
-   [ ] Define a validity test, for a successful deployment.
-   [ ] Automate the deployment of OpenShift
-   [ ] Collect the administrator commands used to provide a fully working TESK deployment
-   [ ] Formalize the previous commands (run by the OpenShift CLI) into a YAML static description
##  Hosted Solution*
Explore the functionalities available and the eventual differences in Kubernetes provided as PaaS (aka Hosted Solution) in:
-   [ ] GCP
-   [ ] Azure
-   [ ] AWS
## Local-machine Solutions*
-   [ ] MiniKube 
Deploy, test and evidences the eventual limitation of a local-machine solution. Provide a receipt for enabling the required MiniKube services, which are disabled by default.
## IaaS*
Evaluate the possible scenarios for providing the instructions for deploying a Kubernetes in an IaaS environment and then standardize the deployment instruction of TESK for this environment. Using Kubernetes terminology, this is referenced as On-Premises VMs. This topic that is actually not strictly related to TESK, but more in general for Kubernetes.
-   [ ] Explore the use of Juju as Configuration Management
-   [ ] Define which is the networking model fits best to TESK in Kubernetes on-premises**
# References
*Official reference explaining the possible solutions for Kubernetes:
[https://kubernetes.io/docs/setup/pick-right-solution/]

**Official reference explaining the Cluster Networking for Kubernetes
[https://kubernetes.io/docs/concepts/cluster-administration/networking/]

**Comment by aniewielska** [comment]
For TESK
